title = 'Counting Spanning Tree (Undirected)'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/1082"

[[tests]]
	name = "example.in"
	number = 4

[[tests]]
	name = "small.cpp"
	number = 10
[[tests]]
	name = "random.cpp"
	number = 5
[[tests]]
	name = "max.cpp"
	number = 3

[params]
	N_MIN = 1
	N_MAX = 500
	M_MIN = 0
	M_MAX = 500000
