title = 'Counting Eulerian Circuits'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/1083"

[[tests]]
    name = "example.in"
    number = 4

[[tests]]
    name = "max_random.cpp"
    number = 2

[[tests]]
    name = "max_random_circuit.cpp"
    number = 4

[[tests]]
    name = "has_isolated_point.cpp"
    number = 4

[[tests]]
    name = "loops.cpp"
    number = 2

[params]
    N_MIN = 1
    N_MAX = 500
    M_MIN = 1
    M_MAX = 200_000
