title = 'Stirling Number of the First Kind (Fixed K)'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/962"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "0.in"
    number = 1
[[tests]]
    name = "1.in"
    number = 1
[[tests]]
    name = "2.in"
    number = 1
[[tests]]
    name = "max_max.in"
    number = 1
[[tests]]
    name = "max_random.in"
    number = 4
[[tests]]
    name = "max_small.in"
    number = 2
[[tests]]
    name = "random.in"
    number = 3
    
[params]
    MOD = 998244353
    K_MIN = 0
    N_MAX = 500000
