title = 'Power Projection of Set Power Series'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/975"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "small.cpp"
    number = 12
[[tests]]
    name = "random.cpp"
    number = 10
[[tests]]
    name = "max_random.cpp"
    number = 3
[[tests]]
    name = "first_zero.cpp"
    number = 3
[[tests]]
    name = "issue1147.in"
    number = 1

[[solutions]]
    name = "naive.cpp"
    wrong = false
    allow_tle = true

[params]
    M_MAX = 100000
    N_MAX = 20
    MOD = 998244353
