title = 'Wildcard Pattern Matching'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/931"

[[tests]]
    name = "example.in"
    number = 4

[[tests]]
    name = "small.cpp"
    number = 5

[[tests]]
    name = "random.cpp"
    number = 5

[[tests]]
    name = "max_random.cpp"
    number = 5

[[tests]]
    name = "all_same.cpp"
    number = 5

[[solutions]]
    name = "solution_ref.cpp"

[[solutions]]
    name = "solution_bruteforce.cpp"
    allow_tle = true

[params]
    S_LEN_MAX = 524288