title = 'Range Affine Range Sum'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/233"
[[tests]]
    name = "example.in"
    number = 1

[[tests]]
    name = "small_random.cpp"
    number = 2
[[tests]]
    name = "small.cpp"
    number = 10
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 3

[[solutions]]
    name = "naive.cpp"
    expect = "RE"

[params]
    N_AND_Q_MAX = 500_000
    MOD = 998244353
