title = 'Sum of Multiplicative Function'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/1118"

[[tests]]
    name = "example.in"
    number = 3
[[tests]]
    name = "small.cpp"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "max.cpp"
    number = 5
[[tests]]
    name = "boundaryA.cpp"
    number = 5
[[tests]]
    name = "boundaryB.cpp"
    number = 5
[[tests]]
    name = "hack_wrong_zky_method.cpp"
    number = 6

[[solutions]]
    name = "min_25_sieve.cpp"
    allow_tle = true

[params]
    N_MAX = 100000000000
    MOD = 469762049
    T_MAX = 10000
    T_sqrtN_MAX = 100000
