title = 'Persistent Range Affine Range Sum'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/760"

[[tests]]
    name = "example.in"
    number = 2
[[tests]]
    name = "max_less_query_types.cpp"
    number = 6
[[tests]]
    name = "max_random.cpp"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "small_random.cpp"
    number = 2
[[tests]]
    name = "small.cpp"
    number = 10

[params]
    N_MIN = 1
    Q_MIN = 1
    N_MAX = 100000
    Q_MAX = 100000
    MOD = 998244353
