title = 'Longest Increasing Subsequence'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/803"

[[tests]]
    name = "example.in"
    number = 2
[[tests]]
    name = "small.cpp"
    number = 5
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "max_random.cpp"
    number = 5
[[tests]]
    name = "hand_max.cpp"
    number = 1
[[tests]]
    name = "hand_min.cpp"
    number = 1

[[solutions]]
    name = "correct.cpp"

[params]
    N_MIN = 1
    A_MIN = 0
    N_MAX = 500_000
    A_MAX = 1_000_000_000
