title = 'Multidimensional Convolution (Circular)'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/746"

[[tests]]
    name = "example.in"
    number = 3
[[tests]]
    name = "small.cpp"
    number = 5
[[tests]]
    name = "twos.cpp"
    number = 3
[[tests]]
    name = "threes.cpp"
    number = 3
[[tests]]
    name = "dim1.cpp"
    number = 3
[[tests]]
    name = "dim2.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 2
[[tests]]
    name = "k0.cpp"
    number = 2

[[solutions]]
    name = "naive.cpp"
    allow_tle = true

[params]
    P_MAX = 1_000_000_000
    K_MAX = 18
    PROD_N_MAX = 262144
