title = 'Rectangle Sum'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/118"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "small.cpp"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 3
[[tests]]
    name = "xy_concentrate.cpp"
    number = 3
[[tests]]
    name = "n_131072.cpp"
    number = 1

[[solutions]]
    name = "naive.cpp"
    expect = "RE"
