title = 'Ordered Set'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/1243"


[[tests]]
    name = "example.in"
    number = 2

[[tests]]
    name = "small.cpp"
    number = 3

[[tests]]
    name = "max_random.cpp"
    number = 32

[[solutions]]
    name = "naive.cpp"
    allow_tle = true

[params]
    N_MIN = 0
    N_MAX = 500_000
    Q_MIN = 1
    Q_MAX = 500_000
    A_MIN = 0
    A_MAX = 1_000_000_000