title = 'Range Set Range Composite'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/829"
[[tests]]
    name = "example.in"
    number = 1

[[tests]]
    name = "small_random.cpp"
    number = 2
[[tests]]
    name = "small.cpp"
    number = 10
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 3
[[tests]]
    name = "fragment.cpp"
    number = 2
[[tests]]
    name = "slide_window.cpp"
    number = 2

[[solutions]]
    name = "naive.cpp"
    allow_re = true
[[solutions]]
    name = "lazyseg.cpp"
    allow_tle = true

[params]
    N_AND_Q_MAX = 500_000
    MOD = 998244353
