title = 'Eulerian Trail (Undirected)'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/25"

[[tests]]
    name = "example.in"
    number = 2

[[tests]]
    name = "small_random.cpp"
    number = 3

[[tests]]
    name = "mid_random.cpp"
    number = 3

[[tests]]
    name = "max_random.cpp"
    number = 3

[[tests]]
    name = "small_random_walk.cpp"
    number = 3

[[tests]]
    name = "mid_random_walk.cpp"
    number = 3

[[tests]]
    name = "max_random_walk.cpp"
    number = 3

[[tests]]
    name = "euler_tour.cpp"
    number = 4

[[tests]]
    name = "many_same_vertex.cpp"
    number = 3

[params]
    T_MIN = 1
    T_MAX = 100_000
    N_MIN = 1
    N_MAX = 200_000
    M_MIN = 0
    M_MAX = 200_000
