title = 'Jump on Tree'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/809"


[[tests]]
    name = "example.in"
    number = 1

[[tests]]
    name = "small_random.cpp"
    number = 5

[[tests]]
    name = "random.cpp"
    number = 5

[[tests]]
    name = "max_random.cpp"
    number = 2

[[tests]]
    name = "uni.cpp"
    number = 1

[[tests]]
    name = "almost_uni.cpp"
    number = 2

[[tests]]
    name = "almost_line.cpp"
    number = 4

[[tests]]
    name = "line.cpp"
    number = 1

[[solutions]]
  name = "tle.cpp"
  expect = "TLE"

[[solutions]]
  name = "doubling_correct.cpp"
  

[params]
    N_MIN = 2
    N_MAX = 500_000
    Q_MIN = 1
    Q_MAX = 500_000
