title = 'Factorize'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/41"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "small.cpp"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "max.cpp"
    number = 1
[[tests]]
    name = "big2.cpp"
    number = 3
[[tests]]
    name = "big2_worse.cpp"
    number = 1
[[tests]]
    name = "big_semiprime_gen.cpp"
    number = 2
[[tests]]
    name = "big_semiprime_random.cpp"
    number = 2
[[tests]]
    name = "pow2.cpp"
    number = 3
[[tests]]
    name = "999381247093216751.cpp"
    number = 1
[[tests]]
    name = "prime_test_special.cpp"
    number = 4
[[tests]]
    name = "prime_test_special_bug.cpp"
    number = 3
[[tests]]
    name = "hack00.cpp"
    number = 1
[[tests]]
    name = "carmichael.cpp"
    number = 1
[[tests]]
    name = "4295098369.cpp"
    number = 1
[[tests]]
    name = "fixed_RNG_buster.in"
    number = 1

[[solutions]]
    name = "fixed_RNG.cpp"
    expect = "TLE"
[[solutions]]
    name = "rho_with_difference_of_square.cpp"
    

[params]
    MAX_Q = 100
    MAX_A = 1_000_000_000_000_000_000
