title = 'Number of Increasing Sequences Between Two Sequences'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/1019"

[[tests]]
    name = "example.in"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "maxi.cpp"
    number = 5
[[tests]]
    name = "special.cpp"
    number = 6

[params]
    N_M_MAX = 131072
    MOD = 998244353