title = 'Sum of Floor of Linear'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/48"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "small.cpp"
    number = 5
