title = 'Point Set Range Frequency'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/769"

[[tests]]
    name = "example.in"
    number = 1

[[tests]]
    name = "small_n.cpp"
    number = 3

[[tests]]
    name = "medium.cpp"
    number = 5

[[tests]]
    name = "max.cpp"
    number = 8

[[tests]]
    name = "many_query_0.cpp"
    number = 4

[[tests]]
    name = "many_query_1.cpp"
    number = 4

[[solutions]]
    name = "slow.cpp"
    allow_tle = true

[[solutions]]
    name = "naive.cpp"
    allow_tle = true

[params]
    N_MIN = 0
    N_MAX = 200_000
    Q_MIN = 0
    Q_MAX = 200_000
    A_MIN = 0
    A_MAX = 1_000_000_000
