title = 'Common Interval Decomposition Tree'
timelimit = 5.0
forum = 'https://github.com/yosupo06/library-checker-problems/issues/744'

[[tests]]
    name = "example.in"
    number = 3
[[tests]]
    name = "small_random.cpp"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 3
[[tests]]
    name = "ascending_order.cpp"
    number = 3
[[tests]]
    name = "descending_order.cpp"
    number = 3
[[tests]]
    name = "swap_random.cpp"
    number = 3
[[tests]]
    name = "almost_straight.cpp"
    number = 3
[[tests]]
    name = "killer_case.cpp"
    number = 5
[[tests]]
    name = "killer_straight.cpp"
    number = 1

[[solutions]]
	name = "other_correct.cpp"
	
[[solutions]]
	name = "WA1.cpp"
	expect = "WA"
[[solutions]]
	name = "WA2.cpp"
	expect = "WA"

[params]
    P_MIN = 0
    N_MIN = 1
    N_MAX = 500_000
    N_SMALL_MAX = 20
    SMALL_SWAP_NUM = 20
