title = 'Inverse Matrix (Mod 2)'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/896"

[[tests]]
    name = "example.in"
    number = 3
[[tests]]
    name = "small_random.cpp"
    number = 8
[[tests]]
    name = "random.cpp"
    number = 4
[[tests]]
    name = "max_random.cpp"
    number = 4
[[tests]]
    name = "random_fullrank.cpp"
    number = 4
[[tests]]
    name = "max_fullrank.cpp"
    number = 4
[[tests]]
    name = "lowrank_max_random.cpp"
    number = 8
[[tests]]
    name = "perm_max_random.cpp"
    number = 2

[params]
    N_MAX = 4096
    MOD = 2
