title = 'Tree Diameter'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/465"

[[tests]]
    name = "example.in"
    number = 1

[[tests]]
    name = "small_random.cpp"
    number = 5

[[tests]]
    name = "random.cpp"
    number = 5

[[tests]]
    name = "max_random.cpp"
    number = 2

[[tests]]
    name = "uni.cpp"
    number = 1

[[tests]]
    name = "line.cpp"
    number = 1

[[tests]]
    name = "hack.in"
    number = 1

[params]
    N_MIN = 1
    N_MAX = 500_000
    C_MIN = 1
    C_MAX = 1_000_000_000
