title = 'Compositional Inverse of Formal Power Series (Large)'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/1112"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "identity.in"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "mid.cpp"
    number = 5
[[tests]]
    name = "max_random.cpp"
    number = 5
[[tests]]
    name = "max_identity.cpp"
    number = 1
[[tests]]
    name = "small_degree.cpp"
    number = 10

[[solutions]]
    name = "small_correct.cpp"
    
    allow_re = true

[params]
    N_MAX = 131_072
    N_MID_MAX = 8_000
    MOD = 998_244_353
