title = 'Deque Operate All Composite'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/815"

[[tests]]
    name = "example.in"
    number = 2
[[tests]]
    name = "small.cpp"
    number = 2
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 3
[[tests]]
    name = "large_max.cpp"
    number = 2
[[tests]]
    name = "large_min.cpp"
    number = 2
[[tests]]
    name = "large_triangle.cpp"
    number = 2

[[solutions]]
    name = "bbst.cpp"
    
[[solutions]]
    name = "naive.cpp"
    expect = "TLE"
