title = 'Conversion from Monomial Basis to Newton Basis'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/986"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "small.cpp"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 3
[[tests]]
    name = "near_65536.cpp"
    number = 5

[params]
    N_MAX = 131072
    MOD = 998244353
