title = 'Vertex Add Subtree Sum'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/167"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "small.cpp"
    number = 5
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "max_random.cpp"
    number = 3
[[tests]]
    name = "line.cpp"
    number = 2

[[solutions]]
    name = "naive.cpp"
    expect = "RE"