title = 'Determinant of Matrix (Arbitrary Mod)'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/750"

[[tests]]
    name = "example.in"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "max_random.cpp"
    number = 5
[[tests]]
    name = "perm_max_random.cpp"
    number = 5
[[tests]]
    name = "signed_overflow.cpp"
    number = 1
[[tests]]
    name = "unsigned_overflow.cpp"
    number = 1
[[solutions]]
    name = "charpoly.cpp"
[params]
    N_MAX = 500
    M_MAX = 1_000_000_000
