title = 'Montmort Number'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/196"

[[tests]]
    name = "example.in"
    number = 2
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "max.cpp"
    number = 3
