title = 'System of Linear Equations (Mod 2)'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/896"

[[tests]]
    name = "example.in"
    number = 3
[[tests]]
    name = "smallest.in"
    number = 4
[[tests]]
    name = "small_random.cpp"
    number = 5
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "max_random.cpp"
    number = 5
[[tests]]
    name = "max_small.cpp"
    number = 2
[[tests]]
    name = "small_max.cpp"
    number = 2
[[tests]]
    name = "max_lowrank.cpp"
    number = 10

[params]
    N_MAX = 4096
    M_MAX = 4096
